version: "3.1"
services:
  undisclosedweb:
    build: .
    ports:
      - "55555:80"
    volumes:
      - ./undisclosed-web:/var/www/html:ro
      - ./undisclosed-web/data:/var/www/html/data
      - ./nft-collection:/nft-collection:ro

volumes:
  persistent:

















